language: ruby

cache: bundler

sudo: false

bundler_args: --without development

rvm:
  - 2.4.2
  - 2.3.4
  - 2.2
  - 2.1
  - 2.0
  - ruby-head
  - jruby-head

before_install: gem install bundler -v 1.15.4
